site_name: k8sdc
site_url: http://k8sdc.io
site_description: k8sdc documentation
site_author: Des Drury (des@drury-family.com)
pages:
  - Home: index.md
  - Project: 
    - Overview: project/overview.md
    - Installation: 
      - Vagrant: project/installation/vagrant.md
      - Digital Ocean: project/installation/digital_ocean.md
      - AWS: project/installation/aws.md
      - Verifying Installation: project/installation/verify_install.md
      - Accessing Services: project/installation/services.md
      - Customising Installation: project/installation/custom_install.md
    - Services:
      - Cluster: 
        - Overview: project/services/cluster/overview.md
        - DNS: project/services/cluster/dns.md
        - Docker Registry: project/services/cluster/registry.md
        - Logging: project/services/cluster/logging.md
        - Monitoring: project/services/cluster/monitoring.md
        - Kube-UI: project/services/cluster/kube-ui.md
      - Infrastructure: 
        - Overview: project/services/infrastructure/overview.md
        - Load Balancing: project/services/infrastructure/load-balancing.md
        - LDAP: project/services/infrastructure/ldap.md
        - Roadmap: project/services/infrastructure/roadmap.md
      - Development: 
        - Overview: project/services/development/overview.md
        - Job Management: project/services/development/job-management.md
        - Artifact Management: project/services/development/artifact-management.md
        - Roadmap: project/services/development/roadmap.md
      - Productivity: 
        - Overview: project/services/development/overview.md
        - Roadmap: project/services/development/roadmap.md
    - Roadmap: project/roadmap.md
  - Guides:
    - Workflow:
      - Overview: guides/workflow/overview.md
      - Infrastructure: guides/workflow/infrastructure.md
      - Development: guides/workflow/development.md
      - Productivity: guides/workflow/productivity.md
    - Application Examples: 
      - Overview: guides/examples/overview.md
      - Static Web Site: guides/examples/static-web-site.md
      - Dynamic Web Site: guides/examples/dynamic-web-site.md
      - Microservice: guides/examples/microservice.md
      - Microservice Collection: guides/examples/microservice-collection.md
      - Complex App: guides/examples/complex-app.md
  - Reference:
    - Utilities: reference/utilities.md
    - Capabilities: reference/capabilities.md
    - Solutions: reference/solutions.md
    - Services: reference/services.md
    - Products: reference/products.md
# repo_url: https://github.com/desdrury/k8sdc/
# google_analytics: ['UA-36723568-3', 'mkdocs.org']
#theme: flatly 