---
- name: Test distribution
  hosts: all-nodes
  tasks:
    - assert:
        that: ansible_os_family == "RedHat"
  tags: confirm_redhat

- name: Configure common components
  hosts: all-nodes
  sudo:  yes
  roles:
    - common
  tags: configure_common

- name: Configure Etcd
  hosts: 
    - etcd
  sudo:  yes
  roles:
    - etcd
  tags: configure_etcd

- name: Configure Flannel
  hosts: 
    - kub-master
    - kub-nodes
  sudo:  yes
  roles:
    - flannel
  tags: configure_flannel

- name: Configure Docker
  hosts: 
    - kub-master
    - kub-nodes
  sudo:  yes
  roles:
    - docker
  tags: configure_docker

- name: Configure Kubernetes
  hosts: 
    - kub-master
    - kub-nodes
  sudo:  yes
  roles:
    - kubernetes
  tags: configure_kubernetes

- name: Configure NFS on Master 
  hosts: kub-master
  sudo: yes
  roles:
    - nfs
  tags: configure_nfs

- name: Configure Cluster Services
  hosts: kub-master
  sudo: yes
  roles:
    - services-cluster
  tags: configure_services_cluster

- name: Configure Infrastucture Services
  hosts: kub-master
  sudo: yes
  roles:
    - services-infrastructure
  tags: configure_services_infrastructure

- name: Configure Development Services
  hosts: kub-master
  sudo: yes
  roles:
    - services-development
  tags: configure_services_development

# - name: Configure Productivity Services
#   hosts: kub-master
#   sudo: yes
#   roles:
#     - services-productivity
#   tags: configure_services_productivity

