---

- name: Read the CA certificate
  slurp:
    src: "/etc/kubernetes/certs/ca.crt"
  register: ca_cert

- name: Read kubecfg.key
  slurp:
    src: "/etc/kubernetes/certs/kubecfg.key"
  register: kubecfg_key

- name: Read kubecfg.crt
  slurp:
    src: "/etc/kubernetes/certs/kubecfg.crt"
  register: kubecfg_crt

- name: Create Romulus directory
  file:
    path:  /home/{{ admin_user }}/{{ infrastructure_namespace }}/romulus/
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
  tags: opendj

- name: Copy Romulus secret file
  template:
    src: romulus/romulus-secret.yaml.j2
    dest: /home/{{ admin_user }}/{{ infrastructure_namespace }}/romulus/romulus-secret.yaml
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"

# Create secret!!!!